### ISSUE TITLE
js file not found: script:js/chosen/chosen.jquery.min

### ISSUE THREAD

**Issue by LEDfan** [owncloud/shorty#104]
Hi

I get an error when I go to the admin panel: 'js file not found: script:js/chosen/chosen.jquery.min'.

Note that I'm running oC8.0

**Comment by arkascha** [comment]
Which version / source of Shorty do you use?

**Comment by LEDfan** [comment]
Both master branch and appstore. I'll provide a patch tomorrow.

**Comment by arkascha** [comment]
Could it be that this is not an issue with one of the Shorty apps, but a general problem with the OC core? 
I fail to get OC-8.0.0RC2 working and I get exactly the same error message. Indeed it appears that all 3rdparty js and css files are simply missing in the release candidate. But there seem to be more issues.

**Comment by LukasReschke** [comment]
You need to move the JS and CSS files into your own app. We're not shipping it anymore as they were never considered part of any public API.

Ref https://github.com/owncloud/core/pull/11983

**Comment by LukasReschke** [comment]
Generally speaking: You can only really rely on jQuery being available as 3rdparty file. All other things may disappear at any time if not explicit in a public API.

**Comment by LEDfan** [comment]
Jep, providing the chosen.min.js, solves the error. But when I want to open the short app it redirects to the files app.
'#

**Comment by arkascha** [comment]
@LukasReschke Thanks for pointing that out. I will take care of that. 
Once more an issue that needlessly inflates app code. If they were never "officially" part of owncloud, then how can it be they got shipped? 
@LEDfan Yep, experiencing that too, no idea what's up so far. This is one of the things I meant with "But there seem to be more issues."...

**Comment by LEDfan** [comment]
I managed to fix the app :) I'll push my changes later today.

**Comment by arkascha** [comment]
I made some house keeping today: 
- upgraded all 3 jquery plugins used by Shorty
- created a clean structure and file name pattern in the 3rdparty section
- created an internal copy of the chosen jquery plugin
This was accompanied by restyling some UI aspects.
