### ISSUE TITLE
owncloud-8 compatibility broken

### ISSUE THREAD

**Issue by arkascha** [owncloud/shorty#112]
OC-8 (RC2) does start with loaded Shorty app, but the app is not usable. 
No more crashes after taking care of issues with backwards incompatible changes of jquery plugins in the OC-core. But when opening the Shorty app one gets sent back to the Files app (the default app). 

@LEDfan This is a separation of the issue from #104.

**Comment by VicDeo** [comment]
@arkascha just a hint:  https://github.com/owncloud/documents/blob/master/appinfo/routes.php#L46

**Comment by arkascha** [comment]
@VicDeo Thanks, indeed I was able to fix that step when I added routes as suggested by AnybodyElse.

**Comment by arkascha** [comment]
Unfortunately that only leads to the next issue. Something connected to translation magic which I do not understand: 

Fatal error: Uncaught exception 'Exception' with message 'js file not found: script:3rdparty/l10n/en serverroot:/srv/www/htdocs/owncloud-8.0.0RC2' in /srv/www/htdocs/owncloud-8.0.0RC2/lib/private/template/resourcelocator.php on line 46

![screenshot-oc8-crash-3](https://cloud.githubusercontent.com/assets/2156237/6097891/1e20de56-afce-11e4-974e-58e14bd2aabb.png)

Very interesting here is the stray "kl" in the upper left corner which I cannot find in my code...

**Comment by PVince81** [comment]
I suspect it might be due to: https://github.com/owncloud/shorty/blob/master/shorty/index.php#L48

"loadScripts()" tries to automatically load translations of the given module. You should not use slashes in module names. You could try changing `loadScripts("shorty/3rdparty", "xxx.js")` to `loadScripts("shorty", "3rdparty/xxx.js")`

It will then try to load translations from "shorty/l10n" instead.
But the bug here might be that the ResourceLocator is not supposed to fail for missing translations.

You might also want to re-run the transifex translation script (if applicable), it will use the new JSON/JS format. So the files will become "shorty/l10n/en.js"

**Comment by LEDfan** [comment]
@arkascha @PVince81 I think I had the app loading by making the changes by @PVince81

**Comment by arkascha** [comment]
Actually no, the opposite is the case...
@PVince81 Unfortunately that is not possible, since that does not play along with the "js/" prefix being added. The only way I found to work is the current notation. Any actually I got it to work in OC-8 now too using the "shorty/3rdparty" notation. 
Turned out the culprit was the "kl" in the end. As suspected an acidential paste (we all know that one...), but in a totally unexpected place! 
Nevertheless thanks!

**Comment by PVince81** [comment]
"kl" ? hmmm could almost be vim keys :wink:

**Comment by arkascha** [comment]
Actually I am old school (some also say just old). It is a 'joe' shortcut :-)

**Comment by arkascha** [comment]
Unfortunately the issue is *not* solved, I was too fast...

**Comment by arkascha** [comment]
Appears you _are_ right in the end, @PVince81. 
But how can I solve this? It would mean I have to create a 3rdparty folder inside the js and css subfolders. That is more than ugly since it means to have to pluck 3rdparty stuff I include apart and place single files somewhere inside my code hierarchy. Very bad design...

**Comment by PVince81** [comment]
I believe that originally the first argument of `addScript()` was not intended to be a path.

Some new functions were added: `addVendorScript(moduleName, scriptPath)`.
From what I see it looks for libraries inside a "vendor" subdir (bower-style).
There's an example here: https://github.com/owncloud/core/blob/master/apps/user_ldap/settings.php#L31

**Comment by arkascha** [comment]
Hm, I see your point, but: 
I am currently digging through the core code again (I HATE having to do that as an app developer...) and for me the method in lib/private/util.php#L362 does exactly what I would expect. So should add the path as expected.

**Comment by arkascha** [comment]
Ah, now I understand! Once more a case that shows that implicit magic is a bad thing in programming: OC tries to be really smart by reusing those paths to load the translation files (mapping the paths)...
That step indeed breaks in this case. 
*sigh*

**Comment by PVince81** [comment]
@Raydiation what do you think ?

**Comment by arkascha** [comment]
I tried to use the addVendorScript(moduleName, scriptPath) method. 
Same result: the script get's loaded, that is not the problem, but then the loading of translation files fails. Question for me is: why does OC try to load translation files for vendor scripts?

**Comment by arkascha** [comment]
Ah, getting closer, one moment...

**Comment by arkascha** [comment]
I can get that to work, though it is ugly in my eyes: different methods used for the same thing, just because core tries to be smarter than the app when dealing with the apps hierarchy layout...
But a question arises, since I already into that trap once before: 
Doesn't using \OC_addVendorScript and \OC_addVendorStyle mean that OC will refuse to install the app from the app store? Because of, how was it called, "unallowed code"?

**Comment by LEDfan** [comment]
Try to do:
````
OCP\Util::addScript ( 'shorty', '../3rdparty/chosen.jquery.min');
````
It worked on my instance :)

**Comment by arkascha** [comment]
@LEDfan 
LOL, that is a clever thing, actually. 
An ugly hack too, but certainly better than the approach with the addVendor...() methods!
Thanks!

**Comment by arkascha** [comment]
@LEDfan Works. I guess this is the "cleanest" solution. Thanks.
