### ISSUE TITLE
Also retrieve favicons from pages that do NOT specify them

### ISSUE THREAD

**Issue by arkascha** [owncloud/shorty#114]
Some pages do not specify the location of a favicon, nevertheless some browsers show one. 
This is based on the browsers _guessing_ the favicons URL by appending 'favicon.ico' to the base url (domain name) and testing...
This is a very ugly thing, but apparently not that uncomon (whyever). Therefore it might make sense for Shorty to follow the same strategy when no icon is found inside the markup.

**Comment by arkascha** [comment]
Hehe,...
Sometimes it pays out not to be too clever but to simply do what has to be done instead :-)
Fixed for good.

**Comment by fredl99** [comment]
Sounds like a learning curve :roller_coaster: 
:smiley: 

Nice work, thanks! :heavy_plus_sign:

**Comment by arkascha** [comment]
Yep. 
The reason why I suddenly accepted the approach is simple: nothing speaks against it any more. 
No additional check is actually required for this. All I do now is simply to assume that there will be a favicon at the guessed location, if none was declared in an explicit manner inside the sites markup. I do not even do a check for it because: the check is done when trying to fetch the favicon the first time (so inside the 'add' or 'edit' dialog). And because caching of icons now finally works this will also be the only attempt. Because the 'blank' delivered upon failure will be delivered from cache in future, which clearly does make sense. So it's a try-at-no-costs situation :-)
