### ISSUE TITLE
Display Shorty section on Admin settings page contents

### ISSUE THREAD

**Issue by wakeup** [owncloud/shorty#119]
Admin page has a content bar which lists all settings of apps available for admin. However, in this list, we cannot see Shorty:

![image](https://cloud.githubusercontent.com/assets/231068/6250165/562b366e-b78c-11e4-9034-2baf08d208cd.png)

**Comment by arkascha** [comment]
Thanks for reporting this! I never saw that navigation. 
An impressive demonstration of blindness towards daily situations :-)

Fixed in branch master, hash b8b577aba2357d74a573f7afed39968f7c73734b
