### ISSUE TITLE
Getting white screen on generated URLs on OC 8.0.3

### ISSUE THREAD

**Issue by arm2arm** [owncloud/shorty#125]
Hi,
I was checking it on OC 8.0.3 it does generates some url like:
https://testcloud.aip.de/public.php?service=shorty_relay&id=ddqm78ck04D
How to incorporate this URL with new .htaccess of OC8.0.3?
I can see in the server side I get always 404 for this URL.
Any hints what can be wrong?

**Comment by arkascha** [comment]
Hi, thanks for the feedback and sorry for the inconveniences...
Unfortunately the issue you point out is known. I can only offer a raw workaround, I sketched that inmy last comments on the apps page in the owncloud "app store": https://apps.owncloud.com/content/show.php/Shorty?content=150401

This is a citation from that source: 
All I can offer for now is a hotfix / a workaround that you can apply if you have writing access to the database your owncloud installation uses: 

INSERT INTO oc_appconfig VALUES ('core','public_shorty_relay','shorty/relay.php');
INSERT INTO oc_appconfig VALUES ('core','public_shorty_qrcode','shorty/qrcode.php');
INSERT INTO oc_appconfig VALUES ('core','public_shorty_query','shorty/query.php');

This correctly registers Shorty's public relaying service as it should be, thus relaying works again as expected. 

---
 I know this is frustrating and I hate do say so, but it looks like I will abandon this (and other) apps I contributed to owncloud. It is simply far too much effort to fix things that get broken with every single minor upgrade of the owncloud core.

**Comment by arm2arm** [comment]
thanks a lot!!!
nice, Now I can relay page and QR code generated correctly.
