### ISSUE TITLE
no base URL on "show QR code refference"  button.

### ISSUE THREAD

**Issue by arm2arm** [owncloud/shorty#127]
Hi,
When I generate QR codes, it is correct.
If I click on show QR code refference button it shows only:
/public.php?service=shorty_qrcode&id=qru3RWoJG
but QR image is generated for:
https://testcloud.aip.de/public.php?service=shorty_relay&id=qru3RWoJG

**Comment by arkascha** [comment]
Most likely the same issue as in #125. 

Sorry for that. I am sure you can find a workaround yourself, looks like I missed one small glitch in the workaround I gave in #125. 

And once more the warning: this app is not maintained any more. It is dead.

**Comment by arkascha** [comment]
Closing this issue as "outdated and not getting updated".
