### ISSUE TITLE
YOURLS Link Shorter integrate

### ISSUE THREAD

**Issue by bymueller** [owncloud/shorty#130]
Hey there,

could you please integrate YOURLS Link Shorter? Thanks!

Best,
Benny

**Comment by arkascha** [comment]
Hi Benny, 
thanks for leaving that comment, however I have to deny this request! 

Two reasons: 
1. as you can see in the app store and also here in the repository this app (like all of owncloud apps I implemented) are discontinued, not maintained any more and have to be considered broken. I invested endless time into these apps, never really got any contributions, this is not how an OpenSource project should work. If you want to step forward and take over some app you are more than welcome and will be happy to assist. 

2. this request has been discussed a few times before, you can see these discussions here on github, on the mailing lists and on the comments to the app on the app store. In all cases these discussions did not lead anywhere: there is no sense in an integration, Shorty and YOURLS server more or less the same purpose, it is an either/or decision. An integration would be painful, consume quite some effort and not really offer any benefits over just using one of the two solutions. Again: if you can contribute additional information or ideas you are very welcome. 

Sorry for the inconvenience. I know that discontinued apps are annoying. But I simply lost interest in offering a one man show over years with lots of people sending requests but no one contributing.
