### ISSUE TITLE
Store and show insertion date

### ISSUE THREAD

**Issue by turgo** [owncloud/shorty#56]
I use shorty mostly as a "read it later" tool. It would be a nice, if the list of shorties could be sorted by insertion date in ascending and descending order.

**Comment by arkascha** [comment]
Feature got implemented and will be part of Shorty-0.5. 
Merged into arkascha/owncloud-shorty//stable7 and into owncloud/shorty//stable7

**Comment by arkascha** [comment]
Will be released as part of Shorty version 0.5.
