### ISSUE TITLE
some Bugs here

### ISSUE THREAD

**Issue by GamesGamble** [owncloud/shorty#75]
Hello,
first iam using ti.ny with ownCloud 7.0.4 stable. when i make an new shorty and click share nothing happens i need to click on the i symbol and then share it works. I dont become any tiny link at the source link and the url in copy menu is blank, but the right tiny link got announced at the top middle notification.

**Comment by arkascha** [comment]
The upcoming Shorty-0.5 will be usage again. Sorry again for the inconveniences.
