### ISSUE TITLE
Targets with invalid character encoding (was: Maximum length of URLs?)

### ISSUE THREAD

**Issue by fredl99** [owncloud/shorty#76]
Re: Shorty 0.4.4, ownCloud 7.0.4 (stable)

Hi,
Trying to manually shorten a URL like this one:
http://www.willhaben.at/iad/kaufen-und-verkaufen/kfz-zubehoer-motorradteile/audi-a6-c4-seitenspiegel-beide-107995093?adId=107995093
Shorty complains: "Sorry, that target is invalid!"
When using the Bookmarklet it results in an "Internal Server Error (500)"  :(

When I manually cut away the portion from the righmost slash up to end of the URL then Shorty will accept it. But that's no useful target then. 

Second: The selected states don't seem to work properly anymore. Any of "closed", "private" or "shared" results in a "forbidden" message when calling the short URL, regardless if or which user is logged in. No login-page appears either. The only working status at the moment is "public".

**Comment by fredl99** [comment]
I think this thread is becoming a bit confusing now. Can you divide it into separate topics again, please?
This answer is about the favicons:
(examples: http://www.webidsupport.com/forumsfavicon.ico http://www.no-access.de/defavicon.ico)

> the pages do not use/define a favicon. 

They do, but the URL in Shorty's table is missing the last slash:
http://www.webidsupport.com/forums/favicon.ico -> works
http://www.no-access.de/de/favicon.ico -> works

> But I actually wonder where you got the favicon-URLs you posted from? 

There's a visual difference between the "empty icon" provided by Shorty and a "missing graphics" icon provided by the browser. (See attachment) 
Right click on the icon and "open picture in new tab" or "copy picture URL" reveals the truth :smile: 

I think I know the reason: Both of these sites use relative links:
`<link rel="Shortcut Icon" href="favicon.ico" type="image/x-icon" />` 
`<link rel="SHORTCUT ICON" href="favicon.ico">`
Whereas absolute links work as they should:
`<link rel="shortcut icon" href="https://ssl.gstatic.com/docs/doclist/images/icon_13_image_favicon.ico">`

So if the base URL would end in a slash in the two examples, the favicon-URL would work, too.

**Comment by fredl99** [comment]
Filtering is not my main interest, so I'm fine as it is anyway.

About the collapsible columns, I will have a look at it, but just as a thought:
> Always remember that many people use small screens. This also is the main motivation for the collapsible columns feature.

Of course I understood the intention behind this feature. The purpose is to give more room for a particular column. So why not make it a single-click action: i.e. clicking the "target" header collapses all other columns to their minimum width at once and expands the "target" column to the remaining space? A second click reverts all columns to their defaults.

Imho that would be nicer than repeatedly collapsing columns until the desired one gets enough room (and still won't be showing the entire content sometimes). Is this technically possible?

**Comment by fredl99** [comment]
> The click behavior is more logically, I think you will like it. 

Yes, I think it's more intuitive this way. Thanks!

> I am not yet happy with the changed visualization of the current sorting order, though. You got a better idea here than the bigger and darker icon? 

A darker triangle is the usual way to emphasize the sorting order, if any. It wouldn't have to be bigger too.

Regarding the single-click expansion mentioned before: The "double-arrow" mouse-pointer would also describe this action better than it does now.

**Comment by fredl99** [comment]
Re: Last access date
> Or did I miss understand your comment "updating of expiration date in list of Shortys:" from two days ago?

You're right, my explanation was misleading. Regardless of the change, the time of the last access was shown in seconds of the Unix epoch afterwards. As I've tried it with the expiration date, I reported it wrong.

> OK, seems to be fixed too now :-)

It is. :white_check_mark:

**Comment by arkascha** [comment]
* favicon extraction issue is fixed
sorry, no idea why I did not spot those links last time I looked. You clearly have the better detective genes of us two :-) Turned out that this was a really primitive bug: the 3 different options to code a reference (url, absolute and relative path) were already coded as different cases, but indeed for the relative path case a slash was missing. So relative favicon references simply never worked. Thanks for spotting this correctly. 

Since this is fixed I won't separate it into a separate issue here.

**Comment by arkascha** [comment]
* Emphasis of the active sorting order: the zooming of the icon is important for barrier reduction. Think of visually impaired users having difficulties with contrasts. I always try to use two separate ways to emphasize something.

**Comment by arkascha** [comment]
About the cursor for expanding a column: 
For me the current cursor _is_ a cursor with two horizontal pointers, one left one right. But this might indeed be a question of the cursor theme loaded. None of the standard browser cursors appears more suited. Or do you suggest to change the _icon_, not the _cursor_ when hovering?

I will experiment with different systems and browsers. I hesitate to generate a custom cursor for this...

**Comment by arkascha** [comment]
* About the logic to collapse a single column or to instead collapse all other columns if a title is clicked: 
The original idea was to allow to define how one does to have the table looking "normally". Note that the app stores which columns are collapsed and which are expanded. It will render the table the same when you use the app the next time. The feature was meant to allow temporarily expand single columns for a better overview. 

Let's see if there is a way to get both ideas into a single solution :-)

**Comment by fredl99** [comment]
favicons:
> Since this is fixed I won't separate it into a separate issue here.

Would have been a cheap opportunity to add to the "fixed issues" :laughing: 

> Emphasis of the active sorting order: 
Think of visually impaired users

In no way I want to sound ignorant. But most browsers/OSs offer high contrast settings these users will 
use anyway. But I won't talk against your decisions with this, since I'm not affected. Maybe a visually impaired user should respond on this.

> For me the current cursor is a cursor with two horizontal pointers, one left one right. 

Yes, same here. And for me it suggests "expand". That's why I meant it would fit to "expand this column to the max" by collapsing all others. Naturally another pointer would be nice for reverting all back to the last state (replace "default widths" as I wrote before, because I didn't consider that these settings are stored somewhere.)

**Comment by arkascha** [comment]
Ah, I see what you mean with the cursor: currently the hovering cursor is the same for both actions: collapse and expand. Indeed misleading. 
Unfortunately there is no opposite standard cursor. I hesitate to use a custom cursor because this cannot fit into more than a single cursor theme...

**Comment by arkascha** [comment]
About separating issues: 
Easiest is to create separate issues for separate things. It is easy to close separately defined issues, it is hard to split separate issues reported in a single entry. 

Though certainly getting feedback, questions and hints on issues at all is always the most important :-)

**Comment by arkascha** [comment]
Hm, doesn't expanding a column to max and collapsing all other columns only make sense for the target and title column, if at all?

**Comment by fredl99** [comment]
Sure. That's were I use this feature anyway. :)
So, "expand to the longest field length (of that column) *or* to the available space (with all other columns collapsed)" would indeed be a better common formula.

**Comment by fredl99** [comment]
A bit on the initial topic. I just saw this:
> Error	PHP	iconv(): Detected an illegal character in input string at shorty/shorty/lib/meta.php#111

Do you need any additional input for this?

**Comment by arkascha** [comment]
I'd say that is the error message thrown by php when trying to process the title with the invalid encoding used by willhaben.at I mentioned 4 days ago in this thread. I implemented a workaround for such issue and for me it works. But that does not mean that the sequence is not illegal any more. It is just ignored now :-)

**Comment by fredl99** [comment]
I'm sorry, it's from "2015-01-02T13:18:26+00:00" But I'm ready to ignore it too ;)

This one is around for a long time and it's still here:
`{"app":"PHP","message":"Call to undefined function p() at \/shorty\/shorty\/templates\/tmpl_wdg_verify.php#39","level":3,"time":"2015-01-02T13:39:28+00:00"}`

**Comment by arkascha** [comment]
Yes, i know that message is still thrown. As said: it is _ignored_ now (the issue) which was not the case before. I cannot change the way willhaben.at encodes their title tag. So this error will always be thrown, also in future, when such an illegal string is processed. 

I separate the issue with the "undefined function p()".

**Comment by fredl99** [comment]
I renamed this issue reflecting the real problem behind it.
Since the original issue is now solved, I'll close here an open a new one regarding the discussion about the tables.
