### ISSUE TITLE
Loading target favicons should not throw warnings when using https

### ISSUE THREAD

**Issue by arkascha** [owncloud/shorty#87]
As pointed out by @fredl99 in issue #77: 
When accessing Shorty the target favicons loaded in the list of single dialogs are typically accessed using http. That results in a warning message about "insecure elements" or similar depending on the client side setup. This is annoying.

**Comment by arkascha** [comment]
I reimplemented the loading the favicons not do make direct requests to remote servers, but to use a new proxy serivce offered by the server side of the app. This way all favicons are consequently loaded from the server itself, no client side request to any remote server is done at all any more. 
This should fix the issue documented here. 

@fredl99 Could I ask you to check this on your system, since you suffer from this issue? 
You have to checkout branch "stable7-favicon". If this reimplementation indeed fixes the issue for you I would merge the modification into stable7. Thanks!

**Comment by fredl99** [comment]
OK, I will report within the next days.

**Comment by fredl99** [comment]
I report:
- no more "unsecure elements" warnings. Good. :white_check_mark: 

- Unfortunately there is still a "missing graphics" icon when the icon seems to be available but couldn't be fetched from the target. :red_circle: 
Looks the same as decribed [here](https://github.com/owncloud/shorty/issues/76#issuecomment-68485481). I would suggest to verify the status-code of the request for the favicon from the target's server and deliver blank.png, if it wasn't found.

- Maybe nobody except me would ever try, but right-clicking on the icons and loading the graphic gives strange results:
 - In the above case (no favicon available) the result is a 404-page "Proudly powered by LiteSpeed Web Server". That's a bit confusing, because it also doesn't look like coming from the own OC-server although the address field says so.
 - A favicon that was fetched before is served, but as plain text. The browser should be informed about the graphical content.
 - One minor issue: If proxy.php is called with an invalid query string (or none at all), it ends in a server error. Not nice. 

Most of this is nagging at a high level, I know. But maybe you'll find some time ...

**Comment by arkascha** [comment]
Hey, great, thanks for testing! 
I will take a look into those issues in the next two days, currently busy trying to finish the reimplementation of the setup of the static backend. That one really is a tough one :-(

**Comment by fredl99** [comment]
No need to hurry on this one. The "unsecure" message is gone and that was the main issue. The rest is now documented and can wait. :sunglasses: 

N.B.: I felt free to add a bit in my last comment.

**Comment by fredl99** [comment]
I wrote:
> In the above case (no favicon available) the result is a 404-page "Proudly powered by LiteSpeed Web Server". 

Of course this 404-page is delivered by the target's server, if the favicon in question has an invalid path which was stored by Shorty. The browser only presents this page under the address of my owncloud (because it is proxied there). 
This can cause some confusion. Therefore I consider it necessary to ensure a favicon (or even better all contents) can be successfully retrieved before proxying them. 

I'm aware of the consequences regarding traffic load and latency. (and coding of course). That's why I would rather do without the icons until a simple but reliable method is found.

**Comment by arkascha** [comment]
Sure, I understood your initial comment the way you made more clear now. 
I agree that this is something that makes sense and I do not hesitate to implement exactly what you suggest: 
Whilst retrieving the favicon from the target server the proxy logic should additionally react on problems and handle them in an explicit manner instead of just forwarding everything coming down the line. 

The only reason why this is not yet implemented is that I currently have some other projects that require quite some time, power and commitment. Please note that shorty is a pure leisure project for me. That also is the main reason why I often ask for contributions and the like :-)

**Comment by fredl99** [comment]
It wasn't meant to put pressure on that, just wanted to clarify what I saw earlier. (When I finally realized by myself what really happened :))
If I were a programmer, I'd really love to contribute in a more productive manner. Unfortunately PHP and JS are not mine ...

**Comment by arkascha** [comment]
I implemented the modification, but I would like to test it a little before pushing it...
Unfortunately the only websites with a broken favicon I can find are those I setup in that specific manner :-( 
Do you have some examples for me?

**Comment by arkascha** [comment]
Merged into arkascha/owncloud-shorty//stable7 and into owncloud/shorty//stable7

**Comment by arkascha** [comment]
@fredl99 Works for me, what about your side?

**Comment by fredl99** [comment]
I just saw the bunch of news here. Give me some time to dig through them all, please :)

**Comment by fredl99** [comment]
Here's an interesting example:

![image](https://cloud.githubusercontent.com/assets/2159787/5794632/1d530146-9f77-11e4-82b4-24d722ae3346.png)

Notice the empty square in the middle line? That's where the Company's logo should be. 
But in this case it's no wonder, because it's neither in the server's root-dir, nor is it referenced in this page. The true URL is http://www.medion.com/at/shop/_ui/medion_default/images/favicon.ico and I have no idea how the browser can find it. But it is shown in the browser's tab.

Favicons seem to be more of a challenge than one might expect. I admit I personally would have given up. Too many points of possible failure. But I don't want to break your willingness to beat them all :8ball:

**Comment by arkascha** [comment]
Hm, Shorty should be able to, no problem there. I will take a look tonight. Thanks for the example. 

Actually I have no idea where this idea comes from that a favicon has to be stored in a certain location. That is not the case! It is simply defined by a specific header entry defining its URL! Shorty parses the head and uses that URL. 

That _should_ work, I assume the missing icons come from incorrectly defined entries which Shorty handles now. 

Let's see tonight with that example.

**Comment by arkascha** [comment]
OK, that was actually a different cause that created that effect. 
Anyway, should be fixed in arkascha/owncloud-shorty//stable7

**Comment by fredl99** [comment]
It's a blank.png now, but sometimes becomes a square. When the table is reloaded it's blank again. Anyway, my list displays only very few real icons. Only five out of 24 entries have one, one line shows the browser's square permanently (that's the google-link). All of the others have the blank.png although the according icons do exist in one way or the other (except the problematic ones with the valid, but misleading URL.)
So:
> I have no idea where this idea comes from that a favicon has to be stored in a certain location. It is simply defined by a specific header entry defining its URL.

I know. But as often, standards are one thing, reality is another. Although it's not recommended by the [W3C](http://de.wikipedia.org/wiki/Favicon), as long as [some sources](http://de.selfhtml.org/navigation/faq.htm#favoriten_icon) are telling something else, people will follow.

Some of the sites follow the rules. Surely these are the ones which are handled correctly. All the others might contain errors, wrong URLs, tags or the like. But anyway, Shorty's users won't care about the reason. All they see is a missing favicon. 
Remember, I didn't insist on the them (I'd still rather leave them away, if they make too many problems).

Some, but not all browsers take a simple approach: When there's no usable tag in the page's header or the icon can't be found by that tag, they simply climb up the path looking for the default filename(s) until they get anything usable.
This way I actually could resolve a URL for each of the missing icons in my current list. One of them was not the same as intended for that page, but who cares. At least the blank space could be filled with something. 
If it works for browsers, wouldn't it be a way for Shorty too?

**Comment by arkascha** [comment]
Hm, I also get the impression that I now see less favicons than before. Strange. 

> I know. But as often, standards are one thing, reality is another. Although it's not recommended by the W3C, as long as some sources are telling something else, people will follow.

True. However: Shorty NEVER displayed favicons not declared in an explicit manner by a specified link. There simply is no code to do so. Keep in mind that there is no automatism here, since an entry in Shorty is not like a page loaded into a browser where the browser might think: hey, i feel lucky today, let's try to guess the location of a favicon. 
So the question is: what previously successfully extracted favicons do I now filter out? That must be the proxying step where I introduced the additional reaction on errors and the like. Seems I react on errors that are none. 

Another thing I don't understand: when reloading the page all icons are reloaded from the server (the new proxy service) instead of getting displayed form the client side cache. although I specifically tell the client to cache those icons. Funny enough that is different when hitting on of the the "reload list" buttons inside Shorty itself (for example the cloud icon in the right side of the top control bar). 
Where is the difference? Seems I have to read more about browsers caching strategy...

Retrieving some of the missing favicons by "climbing up" the (virtual) file hierarchy on the target server side? Hm, I am not a fan of this. It creates a series of unnecessary requests and really slows down meta data retrieval. All this just to work around sites with a poor setup. 
And again: shorty never displayed such favicons, yet now there appear to be less favicons in the list. Looks like I have to dive into that again.

**Comment by fredl99** [comment]
You were very busy these days. Nice work, thanks!
I've switched to master, which should be in line with stable7 as far as I can see. Maybe it's an illusion, but favicons in my table seem to decrease too. Don't know if it has to do with your latest changes, but there's something new in my logfile:
> {"app":"PHP","message":"Undefined variable: favicon at \/serverpath\/to\/**shorty\/lib\/meta.php#176**","level":3,"time":"2015-02-05T14:26:51+00:00"}

Hope this helps.

**Comment by arkascha** [comment]
Hm, got the problem. It is not cause by the glitch you see (fixed that, but that has no effect). Instead my strategy when adding a new Shorty falls short. 
I have to think about that one...

**Comment by arkascha** [comment]
OK, changed the strategy and streamlined the implementation. 
Things seem to work now as expected for adding, editing and listing entries. 
Also caching seems to work which speeds up things quite a lot. 

Could I ask you to give it a try? 

Note that some existing Shortys favicons might not work out of the box. 
That should get fixed if you open and re-save them...

**Comment by fredl99** [comment]
**Good:** Actually a whole bunch of them seems to be handled properly now. I haven't tested my entire list, but some of the problematic ones do appear.

**Not so good:** Some still make problems, although I can't see the reason. The according websites are not known to be exotic. Some examples: 
http://www.router-faq.de/index.php?id=kabel&kabel=y_kabel
http://www.ubuntu-forum.de/index.php
http://nonodes.spunow.co.uk/2014/01/setting-up-dlna-renderer-with-decent.html
*The first link* is a typical case. There seem to be difficulties with query strings, as if Shorty cannot ultimately handle such URLs. I can reproduce this effect with similar sites. Entries like that are not even added to the list.
*The middle one* - I don't know why...
For *the last one* the browser inserts its "missing graphic" icon, which makes me think that all the google services refuse to hand over their favicons. (This one is a blogger.com site and I saw the same effect with a "Google Drive" site earlier.)

**Less good:** Under some circumstances the table disappears and a completely empty page is shown (but with the OC header on top). This can happen when I edit an entry which target is invalid (say, an expired link or so) and save it. Then the page is white. After a reload everything is back again, but the changes of the edited entry are lost. 
It looks similar when I add a new entry (via the Shortlet or in the Web-UI), which is either actually invalid or just not recognized as valid (like the ones above). The entry won't show up, although the page does not go blank in between.

These were the most obvious things I could see with my list and the latest commit from master.

Should I checkout stable7 or any other branch for further testing?

**Comment by fredl99** [comment]
N.B.: I just found this in the log:
{"app":"PHP","message":"readfile(\/oc\/apps\/shorty\/img\/blank.png): failed to open stream: No such file or directory at \/serverpath\/to\/shorty\/proxy.php#106","level":3,"time":"2015-02-07T19:25:59+00:00"}

The "oc" in the first line is wrong because it's my URL-path which differs from the physical server-path. Looking from OC's install directory the correct location of the file is ./apps/shorty/img/blank.png

**Comment by arkascha** [comment]
OK, there indeed was a glitch...
 * http://www.router-faq.de/index.php?id=kabel&kabel=y_kabel
fixed, though pretty slow...
 * http://www.ubuntu-forum.de/index.php (no favicon defined, so no favicon extracted)
I made a separate enhancement request for implicit favicons: #114
 * http://nonodes.spunow.co.uk/2014/01/setting-up-dlna-renderer-with-decent.html
That one is tricky... There IS a favicon defined in the markup, however it is protected. Direct requests are blocked, only returning referrers are granted access. Since the Shorty server does not really visit the page therre is no easy workaround... On top of that the request is not only blocked, but the requester gets redirected to a html page which breaks the favicon display again...
(_why_ do people do such things? )

**Comment by arkascha** [comment]
Fixed the issue with the readfile too...

**Comment by arkascha** [comment]
Issue #114 closed, that was the last issue mentioned in your comment. 
Could you please test again? You tests are so valuable, I sometimes scratch my head how many rounds of beer it's going to be... :-)

**Comment by arkascha** [comment]
OK, came back to this one after having to sort out a horrible mess I left behind with merging things on github. I am simply not good with using git :-(
I'd say the current state of the favicon proxying/retrieval is best that can be done. Everything seems to work for me now with one half exception when testing one of the urls you gave me: 
http://nonodes.spunow.co.uk/2014/01/setting-up-dlna-renderer-with-decent.html
This site blocks direct access to their favicon, it redirects to the index document instead. Even setting a referer heading does not help. Actually I currently do not know hoe they block the requests. At least such rare situations are dealt with using a blank again. Better than something broken :-(

@fredl99 Could I ask you to test this again? 
As said before existing entries might still have problems with the favicon. Open them for editing once, shorty should reload the meta data including the favicon, then save the entry again. Now things should work. 

OC-8 is going to be release wednesday or thursday. 
I would love to release Shorty-0.5 until then. 
The only issue left (AFAIK) is #77 and here only that http authentication effect I still do not understand (there simply is not http auth for OC, so I have no idea how this happens! but I would release nevertheless, this can still be sorted out later from my point of view. 

What do you say?

**Comment by fredl99** [comment]
As said before, the site in question is a blogger.com site. I've seen the same effect on a Google-Drive site earlier. As we know, blogger.com is owned by Google, so complications like that are quite foreseeable, and I would expect them with i.e. youtube-links as well. Never mind about that. ;)

I will test my Shortys and report further.

---
I consider the other issue (#77) much more important because of its potential for privacy and security violation, but will elaborate on it there.

I personally wouldn't hurry things just because of release stress. Better safe than sorry.

**Comment by fredl99** [comment]
BTW:
>  I sometimes scratch my head how many rounds of beer it's going to be... :-) 

Since my profit is a real good App you shouldn't care about the beer account. My hope is to keep it balanced against yours. You deserve much more for the effort to put into this, although the community seems to prefer the spectator's position.

**Comment by arkascha** [comment]
I do confirm your last statement :-(

So thanks even more :-)

**Comment by arkascha** [comment]
I don't see how retrieving the favicon from those last sites left could be implemented without creating a huge overhead (doing multiple network requests per favicon). Therefore I close this issue. 
If newer info exists, a better retrieval idea or a better interpretation of the issue, then it can be reopened or a new issue can be opened.

**Comment by fredl99** [comment]
You're right, it doesn't pay for. 
Blame Google for blocking requests which don't help them with their user-tracking.
