### ISSUE TITLE
undefined function p()

### ISSUE THREAD

**Issue by arkascha** [owncloud/shorty#90]
Reported by @fredl99:

This one is around for a long time and it's still here:
{"app":"PHP","message":"Call to undefined function p() at \/shorty\/shorty\/templates\/tmpl_wdg_verify.php#39","level":3,"time":"2015-01-02T13:39:28+00:00"}

**Comment by redhell** [comment]
When i try to verify the static backend link then i'll get this errow aswell. 
But also my created shortys will end in an error:

"Datei nicht gefunden
Das ausgewählte Dokument wurde auf dem Server nicht gefunden.
Du kannst zur Rückkehr zu ownCloud hier klicken."

**Comment by arkascha** [comment]
I just realize that I never checked the verification dialog when porting Shorty to OC-7. 
It appears the logic has been totally broken by the changes in OC-core. 
::sigh::

**Comment by fredl99** [comment]
@redhell  sounds like a wrong or missing rewrite rule.

**Comment by arkascha** [comment]
@redhell I think @fredl99 is correct, your rewriting aparently does not point to Shortys relay service. 
This is exactly what the validation feature is for - and yes, it is really broken currently. 
Sorry!

Currently rewriting the setup validation of the static backend. 
It got broken by core changes in OC-7, the new implementation will be less arkward. 
The main challenge here is that the validation might have to make an ajax request to a separate domain depending on the setup of the static backend. This clearly violates cross domain security. 
So I have to find a way around that withtout opening a security gap :-)

**Comment by arkascha** [comment]
The verification engine got reimplemented completely. 
Merged into arkascha/owncloud-shorty//stable7 and into owncloud/shorty//stable7
Will be part of Shorty version 0.5

**Comment by arkascha** [comment]
Will be released as part of Shorty version 0.5.
